### ISSUE TITLE
Running with the latest published WP 4 (WDS)

### ISSUE THREAD

**Issue by wclr** [yessky/webpack-mild-compile#2]
Running with the latest published WP 4 on the Web-dev-server start:
```
✖ ｢wdm｣: TypeError: callback is not a function
    at onWatchRun (/app/webpack4/node_modules/webpack-mild-compile/index.js:15:5)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/app/webpack4/node_modules/tapable/lib/Ho
okCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/app/webpack4/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._go (/app/webpack4/node_modules/webpack/lib/Watching.js:40:32)
    at Watching.compiler.readRecords.err (/app/webpack4/node_modules/webpack/lib/Watching.js:32:9)
    at Compiler.readRecords (/app/webpack4/node_modules/webpack/lib/Compiler.js:401:11)
    at new Watching (/app/webpack4/node_modules/webpack/lib/Watching.js:29:17)
    at Compiler.watch (/app/webpack4/node_modules/webpack/lib/Compiler.js:201:10)
    at Compiler.compiler.watch (/app/webpack4/node_modules/webpack-mild-compile/index.js:22:28)
    at wdm (/app/webpack4/node_modules/webpack-dev-middleware/index.js:48:31)
    at new Server (/app/webpack4/node_modules/webpack-dev-server/lib/Server.js:145:21)
```

**Comment by yessky** [comment]
@whitecolor  Try to reinstall the new version of webpack-mild-compile package. It should works now
